name = "personal-website-v2"
main = ".open-next/worker.js"
compatibility_date = "2026-08-20"
compatibility_flags = ["nodejs_compat"]
workers_dev = true
routes = [
  { pattern = "jurgenleka.com/*", zone_name = "jurgenleka.com" },
  { pattern = "www.jurgenleka.com/*", zone_name = "jurgenleka.com" },
]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[r2_buckets]]
binding = "NEXT_INC_CACHE_R2_BUCKET"
bucket_name = "personal-website-v2-cache"

[vars]
# Environment variables are set in Cloudflare dashboard
